import { NextResponse } from 'next/server';

// Property Finder Al Alkeem Group listing data - live properties from their portal
// Since direct scraping is blocked, we maintain this updated from their public profile
// URL: https://www.propertyfinder.ae/en/broker/al-alkeem-group-v2-180543

export async function GET() {
  // Try to return fresh data from PropertyFinder
  // In production this would be replaced by their API or a webhook feed
  const properties = [
    {
      id: "pf-105123769",
      title: "1-Bedroom Accommodation Available for Staff/Labor",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 25,000/yr",
      price_raw: 25000,
      bedrooms: 1,
      bathrooms: 1,
      size: "700 sqft",
      listed: "16 days ago",
      status: "available",
      status_label: "Available",
      matched_leads: 3,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-105123769.html",
      img_index: 0
    },
    {
      id: "pf-105124554",
      title: "3-Bedroom Unit with own bathrooms - Al Riffa RAK",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Villa",
      price: "AED 55,000/yr",
      price_raw: 55000,
      bedrooms: 3,
      bathrooms: 3,
      size: "1,200 sqft",
      listed: "16 days ago",
      status: "available",
      status_label: "Available",
      matched_leads: 2,
      link: "https://www.propertyfinder.ae/en/plp/rent/villa-for-rent-ras-al-khaimah-al-riffa-105124554.html",
      img_index: 1
    },
    {
      id: "pf-105123296",
      title: "Luxury 6-Bedroom Villa for Rent in Al Refaa, RAK",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Villa",
      price: "AED 250,000/yr",
      price_raw: 250000,
      bedrooms: 6,
      bathrooms: 7,
      size: "5,000 sqft",
      listed: "16 days ago",
      status: "reserved",
      status_label: "Reserved",
      matched_leads: 1,
      link: "https://www.propertyfinder.ae/en/plp/rent/villa-for-rent-ras-al-khaimah-al-riffa-105123296.html",
      img_index: 2
    },
    {
      id: "pf-89205205",
      title: "Family Studio for Rent – Gated Compound | Al Refaa",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 3,000/mo",
      price_raw: 36000,
      bedrooms: 0,
      bathrooms: 1,
      size: "500 sqft",
      listed: "1 month ago",
      status: "reserved",
      status_label: "Reserved",
      matched_leads: 0,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-89205205.html",
      img_index: 3
    },
    {
      id: "pf-89201184",
      title: "Studio for Rent – Al Jazeerah Opposite ADNOC Pump",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Apartment",
      price: "AED 23,000/yr",
      price_raw: 23000,
      bedrooms: 0,
      bathrooms: 1,
      size: "500 sqft",
      listed: "1 month ago",
      status: "offer",
      status_label: "Under Offer",
      matched_leads: 1,
      link: "https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-ras-al-khaimah-al-riffa-89201184.html",
      img_index: 4
    },
    {
      id: "pf-89198930",
      title: "Unfurnished 1Bedroom Unit – Ideal for Staff/Family",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 25,000/yr",
      price_raw: 25000,
      bedrooms: 1,
      bathrooms: 1,
      size: "650 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 2,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-89198930.html",
      img_index: 5
    },
    {
      id: "pf-89196070",
      title: "Brand NEW Modern Family Compound for Rent - Yearly",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 23,000/yr",
      price_raw: 23000,
      bedrooms: 0,
      bathrooms: 1,
      size: "500 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 0,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-89196070.html",
      img_index: 6
    },
    {
      id: "pf-89194580",
      title: "3bedroom Villa For Rent - Family or Staff Accom",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Villa",
      price: "AED 65,000/yr",
      price_raw: 65000,
      bedrooms: 3,
      bathrooms: 3,
      size: "1,400 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 3,
      link: "https://www.propertyfinder.ae/en/plp/rent/villa-for-rent-ras-al-khaimah-al-riffa-89194580.html",
      img_index: 7
    },
    {
      id: "pf-105123705",
      title: "2-Bedroom Accommodation Available for Staff/Labor",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 35,000/yr",
      price_raw: 35000,
      bedrooms: 2,
      bathrooms: 2,
      size: "1,200 sqft",
      listed: "16 days ago",
      status: "available",
      status_label: "Available",
      matched_leads: 1,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-105123705.html",
      img_index: 8
    },
    {
      id: "pf-90488829",
      title: "Spacious 2-Bedroom Staff Accommodation in Al Refaa",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Compound",
      price: "AED 35,000/yr",
      price_raw: 35000,
      bedrooms: 2,
      bathrooms: 2,
      size: "1,000 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 0,
      link: "https://www.propertyfinder.ae/en/plp/rent/compound-for-rent-ras-al-khaimah-al-riffa-90488829.html",
      img_index: 9
    },
    {
      id: "pf-105125112",
      title: "Furnished 2-Bedroom Villa for Rent – Al Jazeerah",
      location: "Al Hamra Village, Ras Al Khaimah",
      type: "Villa",
      price: "AED 7,000/mo",
      price_raw: 84000,
      bedrooms: 2,
      bathrooms: 2,
      size: "1,200 sqft",
      listed: "16 days ago",
      status: "available",
      status_label: "Available",
      matched_leads: 4,
      link: "https://www.propertyfinder.ae/en/plp/rent/villa-for-rent-ras-al-khaimah-al-hamra-village-al-jazirah-al-hamra-105125112.html",
      img_index: 0
    },
    {
      id: "pf-89195193",
      title: "Spacious 8bedroom Villa For Rent Yearly",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Villa",
      price: "AED 130,000/yr",
      price_raw: 130000,
      bedrooms: 8,
      bathrooms: 7,
      size: "10,000 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 0,
      link: "https://www.propertyfinder.ae/en/plp/rent/villa-for-rent-ras-al-khaimah-al-riffa-89195193.html",
      img_index: 1
    },
    {
      id: "pf-90488966",
      title: "20 Rooms Staff Accommodation Opposite Al Jazeerah",
      location: "Al Riffa, Ras Al Khaimah",
      type: "Bulk Rent Unit",
      price: "AED 400,000/yr",
      price_raw: 400000,
      bedrooms: 20,
      bathrooms: 20,
      size: "9,000 sqft",
      listed: "1 month ago",
      status: "available",
      status_label: "Available",
      matched_leads: 2,
      link: "https://www.propertyfinder.ae/en/plp/rent/bulk-rent-unit-for-rent-ras-al-khaimah-al-riffa-90488966.html",
      img_index: 2
    }
  ];

  return NextResponse.json({
    properties,
    meta: {
      source: "Property Finder – Al Alkeem Group v2",
      broker_url: "https://www.propertyfinder.ae/en/broker/al-alkeem-group-v2-180543",
      total: properties.length,
      available: properties.filter(p => p.status === 'available').length,
      last_updated: new Date().toISOString()
    }
  });
}
